services:
  cubemap:
    image: falconbi/tm1-cubemap:latest
    ports:
      - "8084:8084"
    volumes:
      - ./config:/app/config
      - tm1_data:/app/cube_map/data
    restart: unless-stopped

volumes:
  tm1_data:
